# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56fa9906042dcf62cdc8a6b60601f770cd40d2b629d0403dbd2e54d67708d7cf9230b009818b09b0e17b93776285ad8d0d0a974fef43567cd435914d81d31749

test:
  secret_key_base: 19b1cad75a0c8dad0ce64a657e8ca7deccbda5bf99c005f911d714946fa911f7f1375f953f0135f28fd7d02f741d930d98c3b9d816618ac0ee8c14e96e101e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
